name:                trial-bot-all
version:             0.1.0.0
github:              "githubuser/trial-bot-all"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trial-bot-all#readme>

dependencies:
- base == 4.13.0.0
- req == 3.1.0
- aeson == 1.4.7.1
- text == 1.2.4.0
- hslogger == 1.3.1.0
- time == 1.9.3
- bytestring == 0.10.10.0
- containers == 0.6.2.1
- config-ini == 0.2.4.0


ghc-options:
- -Wall
- -threaded

library:
  source-dirs: src

executables:
  trial-bot-all-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trial-bot-all

tests:
  trial-bot-all-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trial-bot-all
    - hspec == 2.7.1
